# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spiralwise/Workspace/lucid-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spiralwise/Workspace/lucid-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spiralwise/Workspace/lucid-engine/CMakeFiles /home/spiralwise/Workspace/lucid-engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spiralwise/Workspace/lucid-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lucid

# Build rule for target.
Lucid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lucid
.PHONY : Lucid

# fast build rule for target.
Lucid/fast:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/build
.PHONY : Lucid/fast

lucid/ambient.o: lucid/ambient.cpp.o
.PHONY : lucid/ambient.o

# target to build an object file
lucid/ambient.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/ambient.cpp.o
.PHONY : lucid/ambient.cpp.o

lucid/ambient.i: lucid/ambient.cpp.i
.PHONY : lucid/ambient.i

# target to preprocess a source file
lucid/ambient.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/ambient.cpp.i
.PHONY : lucid/ambient.cpp.i

lucid/ambient.s: lucid/ambient.cpp.s
.PHONY : lucid/ambient.s

# target to generate assembly for a file
lucid/ambient.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/ambient.cpp.s
.PHONY : lucid/ambient.cpp.s

lucid/camera.o: lucid/camera.cpp.o
.PHONY : lucid/camera.o

# target to build an object file
lucid/camera.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/camera.cpp.o
.PHONY : lucid/camera.cpp.o

lucid/camera.i: lucid/camera.cpp.i
.PHONY : lucid/camera.i

# target to preprocess a source file
lucid/camera.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/camera.cpp.i
.PHONY : lucid/camera.cpp.i

lucid/camera.s: lucid/camera.cpp.s
.PHONY : lucid/camera.s

# target to generate assembly for a file
lucid/camera.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/camera.cpp.s
.PHONY : lucid/camera.cpp.s

lucid/cmdctrl.o: lucid/cmdctrl.cpp.o
.PHONY : lucid/cmdctrl.o

# target to build an object file
lucid/cmdctrl.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/cmdctrl.cpp.o
.PHONY : lucid/cmdctrl.cpp.o

lucid/cmdctrl.i: lucid/cmdctrl.cpp.i
.PHONY : lucid/cmdctrl.i

# target to preprocess a source file
lucid/cmdctrl.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/cmdctrl.cpp.i
.PHONY : lucid/cmdctrl.cpp.i

lucid/cmdctrl.s: lucid/cmdctrl.cpp.s
.PHONY : lucid/cmdctrl.s

# target to generate assembly for a file
lucid/cmdctrl.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/cmdctrl.cpp.s
.PHONY : lucid/cmdctrl.cpp.s

lucid/light.o: lucid/light.cpp.o
.PHONY : lucid/light.o

# target to build an object file
lucid/light.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/light.cpp.o
.PHONY : lucid/light.cpp.o

lucid/light.i: lucid/light.cpp.i
.PHONY : lucid/light.i

# target to preprocess a source file
lucid/light.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/light.cpp.i
.PHONY : lucid/light.cpp.i

lucid/light.s: lucid/light.cpp.s
.PHONY : lucid/light.s

# target to generate assembly for a file
lucid/light.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/light.cpp.s
.PHONY : lucid/light.cpp.s

lucid/main.o: lucid/main.cpp.o
.PHONY : lucid/main.o

# target to build an object file
lucid/main.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/main.cpp.o
.PHONY : lucid/main.cpp.o

lucid/main.i: lucid/main.cpp.i
.PHONY : lucid/main.i

# target to preprocess a source file
lucid/main.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/main.cpp.i
.PHONY : lucid/main.cpp.i

lucid/main.s: lucid/main.cpp.s
.PHONY : lucid/main.s

# target to generate assembly for a file
lucid/main.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/main.cpp.s
.PHONY : lucid/main.cpp.s

lucid/mesh.o: lucid/mesh.cpp.o
.PHONY : lucid/mesh.o

# target to build an object file
lucid/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/mesh.cpp.o
.PHONY : lucid/mesh.cpp.o

lucid/mesh.i: lucid/mesh.cpp.i
.PHONY : lucid/mesh.i

# target to preprocess a source file
lucid/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/mesh.cpp.i
.PHONY : lucid/mesh.cpp.i

lucid/mesh.s: lucid/mesh.cpp.s
.PHONY : lucid/mesh.s

# target to generate assembly for a file
lucid/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/mesh.cpp.s
.PHONY : lucid/mesh.cpp.s

lucid/meshloader.o: lucid/meshloader.cpp.o
.PHONY : lucid/meshloader.o

# target to build an object file
lucid/meshloader.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/meshloader.cpp.o
.PHONY : lucid/meshloader.cpp.o

lucid/meshloader.i: lucid/meshloader.cpp.i
.PHONY : lucid/meshloader.i

# target to preprocess a source file
lucid/meshloader.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/meshloader.cpp.i
.PHONY : lucid/meshloader.cpp.i

lucid/meshloader.s: lucid/meshloader.cpp.s
.PHONY : lucid/meshloader.s

# target to generate assembly for a file
lucid/meshloader.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/meshloader.cpp.s
.PHONY : lucid/meshloader.cpp.s

lucid/renderer.o: lucid/renderer.cpp.o
.PHONY : lucid/renderer.o

# target to build an object file
lucid/renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/renderer.cpp.o
.PHONY : lucid/renderer.cpp.o

lucid/renderer.i: lucid/renderer.cpp.i
.PHONY : lucid/renderer.i

# target to preprocess a source file
lucid/renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/renderer.cpp.i
.PHONY : lucid/renderer.cpp.i

lucid/renderer.s: lucid/renderer.cpp.s
.PHONY : lucid/renderer.s

# target to generate assembly for a file
lucid/renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/renderer.cpp.s
.PHONY : lucid/renderer.cpp.s

lucid/shader.o: lucid/shader.cpp.o
.PHONY : lucid/shader.o

# target to build an object file
lucid/shader.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/shader.cpp.o
.PHONY : lucid/shader.cpp.o

lucid/shader.i: lucid/shader.cpp.i
.PHONY : lucid/shader.i

# target to preprocess a source file
lucid/shader.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/shader.cpp.i
.PHONY : lucid/shader.cpp.i

lucid/shader.s: lucid/shader.cpp.s
.PHONY : lucid/shader.s

# target to generate assembly for a file
lucid/shader.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/shader.cpp.s
.PHONY : lucid/shader.cpp.s

lucid/utils.o: lucid/utils.cpp.o
.PHONY : lucid/utils.o

# target to build an object file
lucid/utils.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/utils.cpp.o
.PHONY : lucid/utils.cpp.o

lucid/utils.i: lucid/utils.cpp.i
.PHONY : lucid/utils.i

# target to preprocess a source file
lucid/utils.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/utils.cpp.i
.PHONY : lucid/utils.cpp.i

lucid/utils.s: lucid/utils.cpp.s
.PHONY : lucid/utils.s

# target to generate assembly for a file
lucid/utils.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/utils.cpp.s
.PHONY : lucid/utils.cpp.s

lucid/vertex.o: lucid/vertex.cpp.o
.PHONY : lucid/vertex.o

# target to build an object file
lucid/vertex.cpp.o:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/vertex.cpp.o
.PHONY : lucid/vertex.cpp.o

lucid/vertex.i: lucid/vertex.cpp.i
.PHONY : lucid/vertex.i

# target to preprocess a source file
lucid/vertex.cpp.i:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/vertex.cpp.i
.PHONY : lucid/vertex.cpp.i

lucid/vertex.s: lucid/vertex.cpp.s
.PHONY : lucid/vertex.s

# target to generate assembly for a file
lucid/vertex.cpp.s:
	$(MAKE) -f CMakeFiles/Lucid.dir/build.make CMakeFiles/Lucid.dir/lucid/vertex.cpp.s
.PHONY : lucid/vertex.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Lucid"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lucid/ambient.o"
	@echo "... lucid/ambient.i"
	@echo "... lucid/ambient.s"
	@echo "... lucid/camera.o"
	@echo "... lucid/camera.i"
	@echo "... lucid/camera.s"
	@echo "... lucid/cmdctrl.o"
	@echo "... lucid/cmdctrl.i"
	@echo "... lucid/cmdctrl.s"
	@echo "... lucid/light.o"
	@echo "... lucid/light.i"
	@echo "... lucid/light.s"
	@echo "... lucid/main.o"
	@echo "... lucid/main.i"
	@echo "... lucid/main.s"
	@echo "... lucid/mesh.o"
	@echo "... lucid/mesh.i"
	@echo "... lucid/mesh.s"
	@echo "... lucid/meshloader.o"
	@echo "... lucid/meshloader.i"
	@echo "... lucid/meshloader.s"
	@echo "... lucid/renderer.o"
	@echo "... lucid/renderer.i"
	@echo "... lucid/renderer.s"
	@echo "... lucid/shader.o"
	@echo "... lucid/shader.i"
	@echo "... lucid/shader.s"
	@echo "... lucid/utils.o"
	@echo "... lucid/utils.i"
	@echo "... lucid/utils.s"
	@echo "... lucid/vertex.o"
	@echo "... lucid/vertex.i"
	@echo "... lucid/vertex.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

