# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Users\Seb\Documents\GitHub\lucid-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Users\Seb\Documents\GitHub\lucid-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Users\Seb\Documents\GitHub\lucid-engine\CMakeFiles D:\Users\Seb\Documents\GitHub\lucid-engine\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Users\Seb\Documents\GitHub\lucid-engine\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lucid

# Build rule for target.
Lucid: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Lucid
.PHONY : Lucid

# fast build rule for target.
Lucid/fast:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/build
.PHONY : Lucid/fast

lucid/main.obj: lucid/main.cpp.obj
.PHONY : lucid/main.obj

# target to build an object file
lucid/main.cpp.obj:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/main.cpp.obj
.PHONY : lucid/main.cpp.obj

lucid/main.i: lucid/main.cpp.i
.PHONY : lucid/main.i

# target to preprocess a source file
lucid/main.cpp.i:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/main.cpp.i
.PHONY : lucid/main.cpp.i

lucid/main.s: lucid/main.cpp.s
.PHONY : lucid/main.s

# target to generate assembly for a file
lucid/main.cpp.s:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/main.cpp.s
.PHONY : lucid/main.cpp.s

lucid/shader.obj: lucid/shader.cpp.obj
.PHONY : lucid/shader.obj

# target to build an object file
lucid/shader.cpp.obj:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/shader.cpp.obj
.PHONY : lucid/shader.cpp.obj

lucid/shader.i: lucid/shader.cpp.i
.PHONY : lucid/shader.i

# target to preprocess a source file
lucid/shader.cpp.i:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/shader.cpp.i
.PHONY : lucid/shader.cpp.i

lucid/shader.s: lucid/shader.cpp.s
.PHONY : lucid/shader.s

# target to generate assembly for a file
lucid/shader.cpp.s:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/shader.cpp.s
.PHONY : lucid/shader.cpp.s

lucid/vertex.obj: lucid/vertex.cpp.obj
.PHONY : lucid/vertex.obj

# target to build an object file
lucid/vertex.cpp.obj:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/vertex.cpp.obj
.PHONY : lucid/vertex.cpp.obj

lucid/vertex.i: lucid/vertex.cpp.i
.PHONY : lucid/vertex.i

# target to preprocess a source file
lucid/vertex.cpp.i:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/vertex.cpp.i
.PHONY : lucid/vertex.cpp.i

lucid/vertex.s: lucid/vertex.cpp.s
.PHONY : lucid/vertex.s

# target to generate assembly for a file
lucid/vertex.cpp.s:
	$(MAKE) -f CMakeFiles\Lucid.dir\build.make CMakeFiles/Lucid.dir/lucid/vertex.cpp.s
.PHONY : lucid/vertex.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Lucid
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... lucid/main.obj
	@echo ... lucid/main.i
	@echo ... lucid/main.s
	@echo ... lucid/shader.obj
	@echo ... lucid/shader.i
	@echo ... lucid/shader.s
	@echo ... lucid/vertex.obj
	@echo ... lucid/vertex.i
	@echo ... lucid/vertex.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

